### ISSUE TITLE
FAKEWEB: Unhandled exception

### ISSUE THREAD

**Issue by katrotz** [ctide/fakeweb#23]
I would like to point out that it is not obvious that the url to be registered in the fakeWeb should contain the port.
If you register an URL without the port, fakeWeb will fail to detect the registered URL.
Please add the note in the README file, it might save time for over people.

Thanks for the nice and easy utility.
Cheers!

**Comment by ctide** [comment]
Hmm, we have a bunch of tests that don't explicitly include the port. Is this happening when making a request to a port other than 80?

**Comment by katrotz** [comment]
I apologize for a false alarm, looks like it is not reproducible. 
Closing the ticket.
